name: Agent Manager Build

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'feature/*' ]
    paths: 
      - 'agent-manager/**'
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            paths:
              - 'agent-manager/**'

      - name: Determine Build Environment
        if: steps.changes.outputs.paths == 'true'
        id: set-env
        run: |
          if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') }}; then
            echo "DEV environment"
            echo "ENV_VERSION=v10-dev" >> $GITHUB_ENV
          elif ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}; then
            echo "RC environment"
            echo "ENV_VERSION=v10-rc" >> $GITHUB_ENV
          elif ${{ github.event_name  == 'push' && startsWith(github.ref, 'refs/tags/v') }}; then
            echo "PROD environment"
            echo "ENV_VERSION=v10" >> $GITHUB_ENV
          fi