name: Agent Build

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'feature/*' ]
    paths: 
      - 'agent/**'
      - 'version.yml'
  pull_request:
    branches: [ 'main' ]
    paths: 
      - 'agent/**'
      - 'version.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build and sign agent services
        id: set-env
        run: |
          if ${{ github.event_name == 'push' && github.ref_name == 'feature/*' }}; then
            echo "Agent Deployment to DEV"
          elif ${{ github.event_name == 'pull_request' && github.event.pull_request.state == 'approved' && github.ref_name == 'main' }}; then
            echo "Agent Deployment to RC"
          elif ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}; then
            echo "Agent Deployment to RELEASE"
          