name: Agent Build

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'feature/*' ]
    paths: 
      - 'agent/**'
      - 'version.yml'
  pull_request_review:
    types: [submitted]
    branches: [ 'main' ]
    paths: 
      - 'agent/**'
      - 'version.yml'

jobs:
  check:
    name: Check environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Check environment
        id: set-env
        run: |
          if ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/') }}; then
            echo "Agent Deployment to DEV"
            echo "{environment}={dev}" >> $GITHUB_OUTPUT
          elif ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}; then
            echo "Agent Deployment to RC"
            echo "{environment}={rc}" >> $GITHUB_OUTPUT
          elif ${{ github.event_name  == 'push' && startsWith(github.ref, 'refs/tags/v') }}; then
            echo "Agent Deployment to RELEASE"
            echo "{environment}={release}" >> $GITHUB_OUTPUT
          else
            echo "No deployment"
            echo "{environment}={none}" >> $GITHUB_OUTPUT     
          fi

  test:
    name: Test after
    needs: check
    if: ${{ needs.check.outputs.environment != 'none' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test after
        run: |
          echo "Test after"

