name: Installer Dev

on:
  workflow_run:
    workflows: ["Multi Environment Build"]
    types:
      - completed

jobs:
  check_feature:
    name: Check if feature
    runs-on: ubuntu-latest
    outputs:
      is_feature: ${{ steps.check.outputs.is_feature }}
    steps:
      - id: check
        run: |
          echo ${{ github.event.workflow_run.event }}
          echo ${{ github.event.workflow_run.head_branch }}
          if ${{ github.event.workflow_run.event == 'push' && startsWith(github.event.workflow_run.head_branch, 'feature/') }}; then
            echo "It's a feature"
            echo "is_feature=true" >> $GITHUB_OUTPUT
          else
            echo "It's not a feature"
            echo "is_feature=false" >> $GITHUB_OUTPUT
          fi
  deploy:
    name: Deploy to dev
    needs: check_feature
    if: needs.check_feature.outputs.is_feature == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the right branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Print version.yml
      run: cat version.yml
      