name: Create and Publish Frontend Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show values
        run: |
          echo ${{inputs.image_name}}
          echo ${{inputs.environment}}