name: Docker Image Java
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show values
        run: |
          echo ${{inputs.image_name}}
          echo ${{inputs.environment}}